name: Test
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux-amd64-unit-4-cpu-race
          - linux-386-unit-1-cpu
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.18"
      - env:
          TARGET: ${{ matrix.target }}
        run: |
          case "${TARGET}" in
            linux-amd64-unit-4-cpu-race)
              GOARCH=amd64 PASSES='unit' RACE='true' CPU='4' ./main/test-mr.sh -p=2
              ;;
            linux-386-unit-1-cpu)
              GOARCH=386 PASSES='unit' RACE='false' CPU='1' ./main/test-mr.sh -p=4
              ;;
            *)
              echo "Failed to find target"
              exit 1
              ;;
          esac
